# Generated by Django 5.1.3 on 2024-11-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='data',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Data'),
        ),
    ]
