import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@mantine/core/styles.css";
import "@mantine/tiptap/styles.css";
import "@mantine/notifications/styles.css";
import { ColorSchemeScript, createTheme, MantineProvider } from "@mantine/core";
import { Notifications } from "@mantine/notifications";
import "@mantine/dropzone/styles.css";
import AppShellWrapper from "@/hoc/AppShellWrapper";
import ReduxProvider from "@/hoc/ReduxProvider";
import QueryClientProvider from "@/hoc/QueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = createTheme({
    /** Put your mantine theme override here */
  });
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript
          nonce="8IBTHwOdqNKAWeKl7plt8g=="
          defaultColorScheme="auto"
        />
      </head>
      <body className={inter.className}>
        <ReduxProvider>
          <QueryClientProvider>

          <MantineProvider defaultColorScheme="auto" theme={theme}>
            <AppShellWrapper>
              <Notifications />

              {children}
            </AppShellWrapper>
          </MantineProvider>
          </QueryClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
